In [1]:
import numpy as np

In [2]:
A = np.random.randint(1, 5, (3, 3))
B = np.random.randint(1, 5, (3, 3))

# 2. Mnożenie macierzy jako złożenie mnożenia wierszy przez kolumny

In [3]:
def vv(r, c):
    return np.dot(r, c)

In [4]:
def z2(A, B):
    C = np.zeros(shape=(3, 3)).astype(np.int)
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            C[i, j] = vv(A[i, :], B[:, j])
    return C

In [5]:
z2(A, B)

array([[18, 17, 10],
       [17, 27, 17],
       [19, 25, 19]])

# 4. Mnożenie macierzy (n parzyste) jak blokowe mnożenie wielu macierzy 2x2

In [6]:
def z4(A, B):
    C = np.zeros(shape=(3, 3)).astype(np.int)
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            C[i, j] = A[i, 0] * B[0, j] + A[i, 1] * B[1, j] + A[i, 2] * B[2, j]
    return C

In [7]:
z4(A, B)

array([[18, 17, 10],
       [17, 27, 17],
       [19, 25, 19]])

# Check if result is correct

In [8]:
A @ B

array([[18, 17, 10],
       [17, 27, 17],
       [19, 25, 19]])