In [1]:
from scipy import linalg
import numpy as np
A = np.array([[3, 1], [1, 2]]).astype(np.float32)
A

array([[3., 1.],
       [1., 2.]], dtype=float32)

# 1. Metoda potęgowa obliczania wartości własnych macierzy 2x2

In [2]:
def eigenvalues(A, epsilon):
    eigenvalues = []
    for c in range(A.shape[0]):
        eigenvalue, eigenvector = power_method(A, epsilon)
        eigenvalues.append(eigenvalue)
        A_0 = np.expand_dims(A[0,:].T.shape, 1)
        A -= eigenvector@ A_0 / eigenvector[0]
    return np.asarray(eigenvalues)
        
def power_method(A, epsilon):
    Z = np.array([1, 1]).T
    cnt = 0
    while True:
        W = A @ Z
        eigenvalue = Z.max()
        e = linalg.norm(W - (eigenvalue*Z))
        if e < epsilon:
            break
        
        Z = W / eigenvalue
        cnt += 1
        
    return eigenvalue, np.expand_dims(Z, 1)

In [3]:
eigenvalues(A, 0.1)

array([3.63636364, 1.38287671])

# Check if result is correct

In [4]:
A = np.array([[3, 1], [1, 2]]).astype(np.float32)
linalg.eigvals(A)

array([3.618034+0.j, 1.381966+0.j], dtype=complex64)