In [1]:
import numpy as np
from scipy import linalg
np.set_printoptions(suppress=True)
x = np.expand_dims(np.array([1, 1]), 1).astype(np.float32)
x

array([[1.],
       [1.]], dtype=float32)

# 1. Dla zadanego wektora z R2, tworzenie macierzy odbicia Q i przemnażanie wektora tak żeby wyzerować jego drugą współrzędną

In [2]:
def calc_q(x):
    theta = linalg.norm(x)
    gamma = (x[0] + theta) / theta
    y = np.expand_dims([-theta, 0],1)
    u = (x - y) / (x[0] + theta)
    Q = np.eye(x.shape[0]) - (gamma * u @ u.T)
    return Q

In [3]:
Q = calc_q(x)
Q

array([[-0.70710666, -0.70710674],
       [-0.70710674,  0.7071068 ]])

In [4]:
Q @ x

array([[-1.4142134 ],
       [ 0.00000006]])